---
title: "ccc"
author: "Pierre Nouvellet"
date: "2019-07"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(dplyr )

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), fig.width=10, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )

```

# read data 



```{r}
rel_mse3 <- function(obs, pred,cv) {
    nsims <- ncol(pred)
    # log_l <- rowSums(dpois(x = matrix(obs,7,nsims,byrow = FALSE),lambda = pred+.5,log = TRUE))
    param <- epitrix::gamma_mucv2shapescale(mu = pred+.5, cv =  cv)
    log_l <- rowSums(dgamma(x = matrix(obs+.5,7,nsims,byrow = FALSE),
                            shape = param$shape,
                            scale = param$scale,
                            log = TRUE))
    log_l <- log_l / nsims# (nsims * (obs^2 + 1))
    sum(log_l)
}

```


```{r}
rel_mse2 <- function(obs, pred) {
  nsims <- ncol(pred)
  log_l <- rowSums(
    dpois(
      x = matrix(obs, nrow = 7, ncol = nsims,  byrow = FALSE),
      lambda = pred + .5,
      log = TRUE
    )
  )
  log_l <- log_l / nsims# (nsims * (obs^2 + 1))
  log_l
}

output_files <- list(
  "../DeathToCaseReporting/RData/DeCa_Std_results_week_end_2020-03-08.rds",
  "../DeathToCaseReporting/RData/DeCa_Std_results_week_end_2020-03-15.rds",
  "../DeathToCaseReporting/RData/DeCa_Std_results_week_end_2020-03-22.rds",
  "../DeathToCaseReporting/RData/DeCa_Std_results_week_end_2020-03-29.rds",
  "../DeathToCaseReporting/RData/DeCa_Std_results_week_end_2020-04-05.rds",
  "../Team.output/RtI0_Std_results_week_end_2020-03-08.rds",
  "../Team.output/RtI0_Std_results_week_end_2020-03-15.rds",
  "../Team.output/RtI0_Std_results_week_end_2020-03-22.rds",
  "../Team.output/RtI0_Std_results_week_end_2020-03-29.rds",
  "../Team.output/RtI0_Std_results_week_end_2020-04-05.rds",
  "../Team.output/sbkp_Std_results_week_end_2020-03-08.rds",
  "../Team.output/sbkp_Std_results_week_end_2020-03-15.rds",
  "../Team.output/sbkp_Std_results_week_end_2020-03-22.rds",
  "../Team.output/sbkp_Std_results_week_end_2020-03-29.rds",
  "../Team.output/sbkp_Std_results_week_end_2020-04-05.rds"
)

names(output_files) <- gsub(
  pattern = ".rds", replacement = "", x = output_files
)



model_outputs <- purrr::map(output_files, readRDS)

model_input <- readRDS("../Team.input/data_2020-04-12.rds")

model_predictions_error <- purrr::imap_dfr(
  model_outputs,
  function(x, model) {
    message(model)
    pred <- x[["Predictions"]]
    f <- which(names(pred) %in% model_input$Country)
    pred <- pred[names(pred)[f]]
    purrr::imap_dfr(
      pred,
      function(y, cntry) {
        names(y) <- c("si_1", "si_2")
        out <- purrr::map_dfr(
          y,
          function(y_si) {
            y_si <- as.matrix(y_si)
            y_si <- t(y_si) ## Need T X N matrix for assessr
            dates2 <- as.Date(rownames(y_si))
            x <- dplyr::filter(
              model_input[["D_active_transmission"]],
              dates %in% dates2
            ) %>% pull(cntry)

            if (length(x) > 0) {
              out <- rel_mse2(obs = x, pred = y_si)
              out <- as.data.frame(cbind(out,dates2,dates2[1]))
              out <- tibble::rownames_to_column(out, var = "date")
            } else {
              out <- NULL
            }
            out
          },
          .id = "si"
        )
      },
      .id = "country"
    )
  },
  .id = "model"
  )


d <- model_predictions_error

```

```{r}

country <- sort(unique(as.character(d$country)))
# d$out <- log(d$out)

d$period <- substr(x = d$model, start = 27,stop = 36)
d$period <- as.Date(d$period,format = '%Y-%m-%d')
d$date <- as.Date(d$date,format = '%Y-%m-%d')

periods <- sort(unique((d$period)))

d$model <- substr(x = d$model, start = 1,stop = 25)

# add model number
models <- unique(d$model)
model_num <- rep(NA,nrow(d))
period_num <- rep(NA,nrow(d))
day_week <- rep(NA,nrow(d))
for (i in 1:nrow(d)){
  model_num[i] <- which(models %in% d$model[i])
  period_num[i] <- which(periods %in% (d$period[i]))
  day_week[i] <- as.numeric(d$date[i]-d$period[i])
  
}
d$model_num <- model_num
d$period_num <- period_num
d$day_week <- day_week

table(d$model_num,d$country)

#serial
f <- which(d$si %in% 'si_1')
d1 <- d[f,]


f <- which(d$si %in% 'si_2')
d2 <- d[f,]
```